import json
import argparse
from datetime import datetime

def main():
    parser = argparse.ArgumentParser(description='SDET 5: Markdown Report Builder')
    parser.add_argument('--classified', required=True)
    parser.add_argument('--validated', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--logs-filename', required=True)
    parser.add_argument('--timestamp', required=True)
    
    args = parser.parse_args()
    
    print("📖 Reading validated logs...")
    with open(args.validated, 'r') as f:
        data = json.load(f)
    
    bugs = [e for e in data['entries'] if e.get('classification') == 'GENUINE_BUG']
    flakes = [e for e in data['entries'] if e.get('classification') == 'ENVIRONMENT_FLAKE']
    
    total = len(data['entries'])
    bug_pct = (len(bugs) / total * 100) if total > 0 else 0
    flake_pct = (len(flakes) / total * 100) if total > 0 else 0
    
    report = f"""# 🔍 Log Stream Triager Report

**Generated:** {args.timestamp}
**Source File:** `{args.logs_filename}`
**Model:** Groq (Mixtral-8x7b-32768)

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| **Total Logs Analyzed** | {total} |
| **🐛 Genuine Bugs** | {len(bugs)} ({bug_pct:.1f}%) |
| **🌧️ Environment Flakes** | {len(flakes)} ({flake_pct:.1f}%) |

---

## 🐛 Genuine Bugs ({len(bugs)})

These are **actual code defects** that require immediate attention and code changes.

"""
    
    if len(bugs) > 0:
        for idx, bug in enumerate(bugs, 1):
            error_type = bug.get('error_type', 'Unknown')
            severity = bug.get('severity', 'error')
            confidence = bug.get('confidence', 0.5)
            reasoning = bug.get('reasoning', 'No analysis available')
            
            report += f"""### Bug #{idx}: {error_type}

**Severity:** {severity.upper()}
**AI Confidence:** {confidence:.0%}
**Analysis:** {reasoning}

**Log Excerpt:**
{bug['cleaned'][:500]}

---

"""
    else:
        report += "✅ No genuine bugs detected in this batch.\n\n---\n\n"
    
    report += f"""## 🌧️ Environment Flakes ({len(flakes)})

These are **transient infrastructure issues** that typically auto-recover. No code changes needed.

"""
    
    if len(flakes) > 0:
        report += """| # | Error Type | Severity | Confidence |
|---|-----------|----------|-----------|
"""
        for idx, flake in enumerate(flakes, 1):
            error_type = flake.get('error_type', 'Unknown')
            severity = flake.get('severity', 'warning')
            confidence = flake.get('confidence', 0.5)
            report += f"| {idx} | {error_type} | {severity} | {confidence:.0%} |\n"
    else:
        report += "✅ No environment flakes detected.\n"
    
    report += f"""

---

## ✅ Recommended Actions

### For Genuine Bugs ({len(bugs)})

1. **Immediate Actions:**
   - Assign bugs to development team
   - Create GitHub issues with error details
   - Add reproduction steps

2. **Prioritization:**
   - CRITICAL/ERROR severity → Fix in current sprint
   - WARNING severity → Plan for next sprint

3. **Code Review:**
   - Review error type (NullPointerException, logic error, etc.)
   - Check for similar issues in other files
   - Add unit tests for regression prevention

### For Environment Flakes ({len(flakes)})

1. **Monitoring:**
   - Set up alerts for recurring flakes
   - Monitor infrastructure metrics (CPU, memory, network)
   - Check cloud provider status pages

2. **Configuration:**
   - Increase retry timeouts if needed
   - Scale connection pools
   - Add circuit breakers for external services

3. **Documentation:**
   - Document known flaky services
   - Create runbooks for common failures
   - Update CI/CD troubleshooting guides

---

## 📋 Detailed Findings

**Classification Method:** Groq LLM + Keyword Validation
**Processing Pipeline:** 5-step SDET analysis
**Validation Accuracy:** Cross-referenced with error keywords

### Bug Breakdown by Type

"""
    
    if len(bugs) > 0:
        error_types = {}
        for bug in bugs:
            et = bug.get('error_type', 'Unknown')
            error_types[et] = error_types.get(et, 0) + 1
        
        for error_type, count in sorted(error_types.items(), key=lambda x: x[1], reverse=True):
            report += f"- **{error_type}:** {count} occurrence(s)\n"
    
    report += f"""

---

## 🔧 Next Steps

1. ✅ Review this report
2. 📝 Create GitHub issues for genuine bugs
3. 👨‍💻 Assign to team members
4. 📊 Track bug fixes in sprint
5. 🔄 Monitor environment flakes

---

**Generated by Log Stream Triager**
*Powered by Groq LLM + GitHub Actions*
"""
    
    print("✍️  Writing markdown report...")
    with open(args.output, 'w') as f:
        f.write(report)
    
    print(f"✅ Report generated: {args.output}")
    print(f"   📄 Report size: {len(report)} characters")

if __name__ == '__main__':
    main()